### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lbudzynowski** [Tomin1/wifisignalstrength#2] opened 2018-03-11 19:54 UTC
Hello, 

I would really love to use it but it shows me an error upon turning on. I am not an expert but I "tailed" my syslog and found this: 
Mar 10 20:11:38 Katrina gnome-shell[7905]: Extension "wifisignalstrength@tomin.site" had error: TypeError: NMC.Client is undefined 
Mar 10 20:11:38 Katrina gnome-software[8110]: no app for changed wifisignalstrength@tomin.site 

I am using Ubuntu Bionic.... Please help!

**Comment by Tomin1** [comment] 2018-03-17 19:45
Thank you for reporting this! Ubuntu Bionic has not been released yet, but it's good to test with pre-release software to prepare for the future. I will check this when I have some time to do it.

**Comment by Tomin1** [comment] 2018-08-04 09:09
Closing this issue since the reporter has not confirmed that the fix works but it is probably fixed now.

**Closed as completed by Tomin1** 2018-08-04 09:09 UTC
