### ISSUE TITLE
Crashes Gnome 3.28

### ISSUE THREAD

**Issue by texjoachim** [Tomin1/wifisignalstrength#3] opened 2018-03-17 17:47 UTC
Hi!
I just updated to Gnome 3.28 and found out the hard way that this extension crashes the shell so hard that you can't login anymore.
I removed the extension and was able to login again. Installed the extension again: instant crash without ability to relogin.

Regards,

Joachim

**Comment by Tomin1** [comment] 2018-03-17 19:42
That sounds bad. Thank you for reporting! I'll check that at some point. I wonder if there is any good way to fake a wifi (on Network Manager) with a VM because that would make testing different versions of Gnome easier. The only thing that comes to my mind is to add a real wifi to the VM with USB passthrough (so no faking really).

**Comment by texjoachim** [comment] 2018-03-18 17:42
I'd provide some logs if you tell me where to find them.

**Comment by Tomin1** [comment] 2018-03-24 14:28
I tested this on my old laptop where I installed Fedora 28 test build. It seems that Gnome Shell crashes if NetworkManager-glib is installed and this extension is loaded. For some reason an assertion error happens and Gnome Shell crashes.
```
maalis 24 10:12:37 localhost.localdomain gnome-shell[5640]: libnm symbols detected; Mixing libnm with libnm-util/libnm-glib is not supported
maalis 24 10:12:37 localhost.localdomain audit[5640]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=9 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=5640 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=5 res=1
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: == Stack trace for context 0x55bbd45c2020 ==
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #0 0x55bbd4714a20 i   /home/tomi/.local/share/gnome-shell/extensions/wifisignalstrength@tomin.site/extension.js:60 (0x7f51db37e780 @ 392)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #1 0x7fff07892a50 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f51f16b4de0 @ 71)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #2 0x55bbd4714998 i   /home/tomi/.local/share/gnome-shell/extensions/wifisignalstrength@tomin.site/extension.js:90 (0x7f51db37e9a0 @ 15)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #3 0x55bbd47148e8 i   resource:///org/gnome/shell/ui/extensionSystem.js:129 (0x7f51f1454ab0 @ 408)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #4 0x55bbd4714850 i   resource:///org/gnome/shell/ui/extensionSystem.js:171 (0x7f51f1454bc0 @ 241)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #5 0x55bbd47147d0 i   resource:///org/gnome/shell/ui/extensionSystem.js:318 (0x7f51f145b340 @ 13)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #6 0x7fff07894150 b   resource:///org/gnome/gjs/modules/signals.js:126 (0x7f51f16cff78 @ 386)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #7 0x55bbd47146f0 i   resource:///org/gnome/shell/misc/extensionUtils.js:184 (0x7f51f145ba28 @ 360)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #8 0x7fff07894d90 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f51f16b4de0 @ 71)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #9 0x55bbd4714660 i   resource:///org/gnome/shell/misc/extensionUtils.js:190 (0x7f51f145bb38 @ 28)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #10 0x7fff07895a40 b   resource:///org/gnome/shell/misc/fileUtils.js:27 (0x7f51f145bc48 @ 323)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #11 0x55bbd47145d0 i   resource:///org/gnome/shell/misc/extensionUtils.js:189 (0x7f51f145bab0 @ 72)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #12 0x7fff07896670 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f51f16b4de0 @ 71)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #13 0x55bbd4714540 i   resource:///org/gnome/shell/ui/extensionSystem.js:320 (0x7f51f145b2b8 @ 201)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #14 0x55bbd47144c0 i   resource:///org/gnome/shell/ui/extensionSystem.js:328 (0x7f51f145b3c8 @ 36)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #15 0x55bbd4714440 i   resource:///org/gnome/shell/ui/extensionSystem.js:359 (0x7f51f145b5e8 @ 67)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #16 0x55bbd47143b8 i   resource:///org/gnome/shell/ui/extensionSystem.js:367 (0x7f51f145b670 @ 41)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #17 0x55bbd4714328 i   resource:///org/gnome/shell/ui/main.js:229 (0x7f51f16de120 @ 1152)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #18 0x55bbd47142a0 i   resource:///org/gnome/shell/ui/main.js:133 (0x7f51f16d8f78 @ 237)
maalis 24 10:12:37 localhost.localdomain org.gnome.Shell.desktop[5640]: #19 0x55bbd4714228 i   <main>:1 (0x7f51f1686b38 @ 48)
maalis 24 10:12:47 localhost.localdomain gnome-shell[1093]: g_array_free: assertion 'array' failed
```

If I don't have NetworkManager-glib installed, the extension won't work but it also doesn't crash the shell:
```
maalis 24 10:14:09 localhost.localdomain gnome-shell[6098]: Extension "wifisignalstrength@tomin.site" had error: Error: Requiring NetworkManager, version none: Typelib file for namespace 'NetworkManager' (any version) not found
```

I got these logs with `journalctl /usr/bin/gnome-shell`. The former error could be something to report to Gnome Shell developers so they could harden the shell against this if they will. The latter is best fixed by updating the extension to use the new NetworkManger API, nmlib. I will look into this and it will probably fix this bug and bug #2 as well.

**Comment by Tomin1** [comment] 2018-03-25 12:31
I just pushed commit c4004b4 that should fix this issue. I will test this with older versions of Gnome Shell (whether the extension still works or not) and update metadata.json accordingly. After that I will release a new version of the extension.

**Comment by wojciech-zurek** [comment] 2018-03-25 19:37
I can confirm that older version is crashing gnome 3.28.
But Your latest commit https://github.com/Tomin1/wifisignalstrength/commit/c4004b4bca926468d26112f4c452337a9116e426
is working for me.

**Comment by Tomin1** [comment] 2018-03-25 19:44
Apparently the latest code does not work with Gnome 3.26 because now they mix the old and new Network Manager interfaces, which is causes a crash but this time Gnome is the one with old code. I need to think about this since I would very much like to support a few of the latest versions of Gnome. I may need to somehow choose dynamically the interface that I use based on Gnome Shell version.

**Comment by Tomin1** [comment] 2018-04-25 15:15
I made a new version to branch gnome-3.28. I will test it on multiple Gnome versions and release later this week on extensions.gnome.org (unless it doesn't work and I can't fix it, but I doubt that will happen). Currently it is completely untested, I just wrote the code on a machine that doesn't have Wifi.

**Comment by deep414** [comment] 2018-05-27 20:19
I have the same issue and can not log in to my account.
I wonder if there is a recipe on how to reset the extension?

**Comment by Tomin1** [comment] 2018-05-27 20:28
You can login on a virtual terminal (e.g. Ctrl+Alt+F2) and use command `gnome-shell-extension-tool -d wifisignalstrength@tomin.site` to disable the extension. Then logout (`exit`) and go back to graphical terminal (Alt+F1 or Alt+F7 usually).

I have submitted a new version for review to extensions.gnome.org but it still hasn't been reviewed.

**Comment by deep414** [comment] 2018-05-28 16:44
Hello,

unfortunately this did not help. I tried several times, check the command.
Nothing happened.

With best regards,

Alexei Kozlov

2018-05-27 23:28 GMT+03:00 Tomi Leppänen <notifications@github.com>:

**Comment by Tomin1** [comment] 2018-05-28 19:56
Did you login to the virtual terminal first? Just checking because I really don't have any idea how proficient you are with Linux. The command should print that it disabled the extension. After that you may try logging in again and Gnome should not crash unless there is something else wrong with it.

**Comment by deep414** [comment] 2018-05-28 20:06
Hello,

yes.

when I just boot the machine and come to graphic logon screen
I did:
1. ALT+CTRL+F2
2. Login as my userid (alexei)
3. then execute command you sent.
    i checked it several time for correct spell
4. it said that extension is disabled.
5. did CTRL+D
Then Alt+F1
and tried to login to my userid via graphic screen.
And then I saw the same result.
...
On my machine I have two userids:
alexei - my general ID
test - for testing. I write email in test userid.

Alexei

2018-05-28 22:56 GMT+03:00 Tomi Leppänen <notifications@github.com>:

**Comment by deep414** [comment] 2018-05-28 20:13
Hello,

don't worry.
I thought to reinstall Fedora from scratch anyway.
Data is save, I will copy it to my backup media and will reinstall the
system during this weekend.


2018-05-28 22:56 GMT+03:00 Tomi Leppänen <notifications@github.com>:

**Comment by Tomin1** [comment] 2018-08-04 09:08
Closing this issue since the reporter has not confirmed it but it should be fixed.

**Closed as completed by Tomin1** 2018-08-04 09:08 UTC
